export const specialties = [
  'Típica Argentina',
  'Italiana',
  'Mediterránea',
  'Vegana',
  'Fitness',
  'Comida rápida',
  'Peruana',
  'China',
  'Hindú',
  'Japonesa',
  'Mexicana',
  'Brasileña',
  'Colombiana',
  'Venezolana',
  'Chilena',
  'Uruguaya',
  'Cubana',
  'Ecuatoriana',
  'Costarricense',
  'Dominicana'
];
