export { default as Card } from './Card/Card';
export { default as Cards } from './Cards/Cards';
export { default as FormRest } from './Forms/FormRestaurante';
export { default as Home } from './Home/Home';
export { default as Landing } from './Landing/Landing';
export { default as Login } from './Login/Login';
export { default as Menu } from './Menu/Menu';
export { default as Navbar } from './Navbar/Navbar';
// export { default as Pagination } from './Pagination/Pagination';
export { default as Profile } from './Profile/Profile';
// export { default as Register } from './Register/Register';
export { default as Reviews } from './Reviews/Reviews';